### ISSUE TITLE
shadow.roottn.bak

### ISSUE THREAD

**Issue by evrynet1** [CpanelInc/tech-CSI#11]
Hi Peter,

This is not an issue but a question. I'm sorry if this should be asked elsewhere. Traces of shadow hacks has been found on the server and detected by csi.pl as follows:

> Found the following directories containing the shadow.roottn.bak hack:
    \_ See: https://github.com/bksmile/WebApplication/blob/master/smtp_changer/wbf.php
       \_ /home/xxx1/etc/hon/shadow.roottn.bak
       \_ /home/xxxx2/etc/hi/shadow.roottn.bak

Listing the content of the folders there are shadow and shadow.roottn.bak with the later the older. My question is that shadow.roottn.bak is the original file before the hack happened and shadow file is the newer with the compromised password?

drwxr-x--- 2 pftop pftop 4096 Mar 28 04:33 @pwcache
-rw-r--r-- 1 pftop pftop  119 Mar 29 12:26 shadow
-rw-r----- 1 pftop pftop  119 Apr 10  2021 shadow.roottn.bak

Can you advise here? Would really appreciate.

Thank you

**Comment by cPanelPeter** [comment]
Hello,  

No need to apologize.  This hack started off by backing up the shadow file to shadow.roottn.bak and then removed all email accounts,  leaving only one.  That was likely caused by a bug within their script. It was supposed to append their email account and not remove the rest.   This was why it was first caught. 

Over the years, that bug got fixed, and in some cases, the backup file either didn't exist or was named something else (shadow.z453sx, for example).  There are likely newer scripts that do more or worse, but the wbf.php script was likely the first iteration.  

Sometimes you can trust the shadow.roottn.bak file as a valid backup, and sometimes you can't.  The best solution is always to restore from known good backups, but if you don't have any backups, and only have the shadow. roottn.bak file, then that's another way to go to get you back up and running.

Does that help?

**Comment by evrynet1** [comment]
@cPanelPeter perfectly, thank you for the explanation.
