### ISSUE TITLE
Issues using ./csi.pl --rootkitscan

### ISSUE THREAD

**Issue by Vudubond** [CpanelInc/tech-CSI#4]
When using ./csi.pl --rootkitscan Im getting:

Use of uninitialized value $rkhunterinstall in concatenation (.) or string at ./csi.pl line 1663.
mv: cannot move `/root/CSI/' to a subdirectory of itself, `/root/CSI/rkhunterinstall'
[WARN]: RKHunter installation failed!
[ Installing latest chkrootkit ]
Use of uninitialized value $chkrootkitinstall in concatenation (.) or string at ./csi.pl line 1693.
mv: cannot move `/root/CSI/' to a subdirectory of itself, `/root/CSI/chkrootkit'

CentOS release 6.10

/usr/local/cpanel/cpanel -V
74.0 (build 4)

**Comment by suedeyoung** [comment]
This seems to be a limitation with CentOS 6 with the mv command being run on the installation. Not sure if they removed that check-in CentOS 7 since it is only doing it on 6. 

Tried a few different workarounds on the coding related to it but I wasn't really able to find anything that would work on it. The only thing that I can think of at this point would be to update the script to save it instead of at /root/CSI/rkhunterinstall from /root/CSI/ we can instead perhaps have it move the files to something like /root/rkhunterinstall/CSI so it doesn't trigger mv's check on CentOS 6?

**Comment by cPanelPeter** [comment]
Working on a fix now. 
Thanks.

**Comment by cPanelPeter** [comment]
This is fixed now.  Thank you for reporting it.
